### PR TITLE
Fix capitalization of RunTimeException usages

### PR DESCRIPTION
**Pull request by thiemowmde**

### CODE REVIEW

**Comment by grogy** [comment]
I don't like this PR. Because I think that `RuntimeException` is standard name. [1][2]

[1] https://secure.php.net/manual/en/class.runtimeexception.php
[2] https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html

**Comment by Vrtak-CZ** [comment]
This is not fix. Because in PHP source is `RuntimeExeption`.

- https://github.com/php/php-src/blob/250938e2d35fc54161a18167b7901c5e3b574371/ext/spl/spl_exceptions.c#L63
- https://github.com/php/php-src/blob/250938e2d35fc54161a18167b7901c5e3b574371/ext/spl/spl.php#L100

**Comment by thiemowmde** [comment]
You realize that this class does not uses PHP's `\RuntimeException` but `\JakubOnderka\PhpParallelLint\RunTimeException`?

**Comment by JeroenDeDauw** [comment]
+1

This is indeed not  reference to PHP's `RuntimeException`, though the confusion is understandable. It's weird this package choose `RunTimeException` as capitalization for its own definition.

**Comment by grogy** [comment]
Why do it? I still don't see reason for this modification. Standard name in PHP is `RuntimeExeption`. Why do rename it?

**Comment by JeroenDeDauw** [comment]
This is not a rename. It fixes the capitalization of references to match that of the actual name.

**Comment by grogy** [comment]
:+1: 

Ahh.. I am so sorry. I see it now.. It fixes definition [here](https://github.com/JakubOnderka/PHP-Parallel-Lint/blob/master/src/exceptions.php#L45)

**Comment by JakubOnderka** [comment]
Thanks guys :)

**Pull request merged**
