### PR TITLE
Split autoload

### PR DESCRIPTION
**Pull request by edmondscommerce**
splitting autoload into normal and dev

https://github.com/maglnet/ComposerRequireChecker/issues/92#issuecomment-458905436

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I'd welcome this change 👍

**Comment by edmondscommerce** [comment]
build failed on AppVeyor though doesnt look to be code related, something windowsy that I have no idea about I'm afraid

**Comment by VasekPurchart** [comment]
@edmondscommerce  please do not update this branch with code, that should not go in:

 * changing gitignore (you should use a global or local gitignore)
 * updating composer package name - you should not even do this outside of this PR - it is discouraged as there are more ways how to use your own branch of the code, for example: https://getcomposer.org/doc/04-schema.md#repositories

If you include such unrelated changes, you are lowering (or in the 2nd point downright blocking) this from being merged. Which is sad, because otherwise this would ofc be a welcome change.

**Comment by edmondscommerce** [comment]
Apologies didn't intend for the composer name change stuff to be in this PR

I started work on a harder fork as I wondered if this version was abandoned. Clearly not so I will revert this shortly

**Comment by edmondscommerce** [comment]
@VasekPurchart - PR updated to only include the split of src and test autoload configs

**Comment by VasekPurchart** [comment]
Great, thanks. Not abandoned, I guess the author is just a little busy ATM.

**Pull request closed without merging**
