### PR TITLE
Issue #69 fix proposal

### PR DESCRIPTION
**Pull request by lamskoy**

### CODE REVIEW

**Comment by grogy** [comment]
Thanks. Can you add the unit test?

**Comment by lamskoy** [comment]
Wish I could have some free time for unit tests too :)

**Comment by lamskoy** [comment]
Btw why not PHPunit used?

**Comment by grogy** [comment]
It's good question. PHPUnit isn't used because it is too big and too complex tool. Here is used [Nette Tester](https://github.com/nette/tester) - it's very easy to use tool. Would you help with it?

**Comment by JakubOnderka** [comment]
Hi! Many thanks for your report and pull request, but your solution has problem if a filename contains ` in ` – I know that this must be very rare, but human nerver knows :) So I commited into repository own solution. 

I am looking forward for your next patches and reports.

**Pull request closed without merging**
