### PR TITLE
Added option --version

### PR DESCRIPTION
**Pull request by o5**
Closes https://github.com/JakubOnderka/PHP-Parallel-Lint/issues/71.

### CODE REVIEW

**Comment by grogy** [comment]
Hello,

thanks for your idea and first version of PR. 👍 

Nice - this works, but...:

- File `parallel-lint.php` is base file for tool. It is not good place for show versions.
- Source of code has class `Settings` [1]. I mean it is better place for check input parameters.
- Maybe is in source better place where is possible define and run function `showVersion`.

[1] https://github.com/JakubOnderka/PHP-Parallel-Lint/blob/master/src/Settings.php

Sorry for my critics comment. I mean that my reaction helps you with better code. I can help you - ask me, when you can :-)

**Comment by chasebolt** [comment]
@o5 would love to see this PR merged in 👍 . it's nice to output the version of an app during CI testing.

**Comment by o5** [comment]
@chasebolt I spend 1 hour with this PR and I don't want more. Sorry.

**Comment by chasebolt** [comment]
@JakubOnderka can this get merged?

**Comment by JakubOnderka** [comment]
@o5 Thanks for your pull request

**Pull request merged**
