### PR TITLE
support for Nette Tester (extension .phpt)

### PR DESCRIPTION
**Pull request by mzk**

### CODE REVIEW

**Comment by grogy** [comment]
Thanks for you the pull-request, it looks good.

Why are you meaning that it is good idea? Option for change / add file extension exists now.

**Comment by mzk** [comment]
Because of more strict default values are better. IMHO.

**Comment by VasekPurchart** [comment]
How is it more strict though? If it were more strict, there would be only `.php` :)

So it is quite the opposite.

**Comment by mzk** [comment]
I mean more sensitive, check all possible file extensions by default.

**Comment by JakubOnderka** [comment]
It is OK, thanks! New version will be released soon.

**Pull request merged**
