### PR TITLE
Travis: test against PHP 7.4

### PR DESCRIPTION
**Pull request by jrfnl**
Note: for the time being the build will fail.

* PHP-Parallel-Lint itself has an issue - see #143. 
* Looks like the `nette/tester` package at the `~1.3` version is not compatible with PHP 7.4. The latest release is `2.3.0`, but the 2.x branch requires PHP 5.6 for `~2.0` and PHP 7.1 for `^2.1`.
    The last release in the `1.x` series, `1.7.2` may or may not still contain the issue on which the build is currently failing, but won't be updated anymore either way.
    See: https://github.com/nette/tester/releases
    PR #147 should fix this.
* PHPCS won't be compatible with PHP 7.4 until version 3.5.0 has been released.
    PR #146 should fix this part of the build failure.

### CODE REVIEW

**Comment by jrfnl** [comment]
Test build showing that when this + the above mentioned other PRs are all merged, the Travis builds will pass again: https://travis-ci.org/jrfnl/PHP-Parallel-Lint/builds/573466143

**Comment by jrfnl** [comment]
As PHP 7.4 has come out, I've removed the "allowed to fail" part of the PR and as Travis now has an official PHP 7.4 image available, I've swopped out `7.4snapshot` for `7.4`.

**Comment by grogy** [comment]
Hi,

I am using your PR for solve problems. Because author of this great tool does not communicate so I [created fork](https://github.com/grogy/PHP-Parallel-Lint). You can use it from packagist. Now is out new release with PHP 7.4 support.

**Comment by jrfnl** [comment]
Closing as this has been merged in the new repo: https://github.com/php-parallel-lint/PHP-Parallel-Lint

**Pull request closed without merging**
